### ISSUE TITLE
Interaktion: Kiste von Palette nehmen und auf Wagen stellen

### ISSUE THREAD

**Issue by keckluis** [MarKs1991/Interaktionsdesign#3]

**Comment by MarKs1991** [comment]
Platzierung auf Wagen implementiert, 
Reminder;
Kiste nehmen fehlt noch, interaktions Komponente an Kisten anbringen

**Comment by MarKs1991** [comment]
Reminder: Check falls nachstes item in bestellung wurde bereits gepickt bevor es kronologisch drankommt

**Comment by MarKs1991** [comment]
Notification wenn kiste im collider die überschüssig ist
